import * as esbuild from 'esbuild';
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs';

const watch = process.argv.includes('--watch');

// Clears a generated folder but keeps the folder itself, so a Dropbox "ignored"
// mark on it survives the build. Retries ride out a sync client briefly holding
// a file (EPERM/EBUSY on Windows).
function emptyDir(dir) {
  mkdirSync(dir, { recursive: true });
  for (const e of readdirSync(dir)) rmSync(`${dir}/${e}`, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 });
}

// KaTeX stylesheet + fonts for the webview. The webview is Chromium, which
// takes the first format each @font-face lists (woff2), so the woff and ttf
// copies would only add weight to the package.
emptyDir('media/katex');
writeFileSync(
  'media/katex/katex.min.css',
  readFileSync('node_modules/katex/dist/katex.min.css', 'utf8').replace(/,url\(fonts\/[^)]+\.(woff|ttf)\) format\("(woff|truetype)"\)/g, ''),
);
cpSync('node_modules/katex/dist/fonts', 'media/katex/fonts', { recursive: true, filter: (f) => !/\.(woff|ttf)$/.test(f) });
cpSync('webview/style.css', 'media/style.css');
cpSync('webview/features.css', 'media/features.css');
// Mermaid, loaded by the webview only for documents with a diagram. The ES
// module build splits each diagram type into its own chunk, so a flowchart
// loads a fraction of the library. Source maps are left out.
emptyDir('media/mermaid');
cpSync('node_modules/mermaid/dist/mermaid.esm.min.mjs', 'media/mermaid/mermaid.esm.min.mjs');
cpSync('node_modules/mermaid/dist/chunks/mermaid.esm.min', 'media/mermaid/chunks/mermaid.esm.min', {
  recursive: true,
  filter: (src) => !src.endsWith('.map'),
});

// Writing fonts for the reading panel's "More fonts" (src/readingFonts.ts). Only
// the Latin and Latin Extended files (Turkish, most European languages); other
// scripts fall back to system fonts. The browser loads a file only when its
// font is in use, so the list costs nothing until a font is picked.
const list = await esbuild.build({ entryPoints: ['src/readingFonts.ts'], bundle: true, write: false, format: 'esm', logLevel: 'silent' });
const { EXTRA_FONTS, fontStack } = await import(`data:text/javascript;base64,${Buffer.from(list.outputFiles[0].text).toString('base64')}`);
emptyDir('media/fonts');
mkdirSync('media/fonts/licenses', { recursive: true });
const faces = [];
const looks = [];
const LEADING = { sans: 1.72, serif: 1.75, mono: 1.8 };
for (const f of EXTRA_FONTS) {
  if (f.source.ia) {
    for (const [file, style, weight] of [['Regular', 'normal', 400], ['Italic', 'italic', 400], ['Bold', 'normal', 700], ['BoldItalic', 'italic', 700]]) {
      const name = `${f.source.ia}-${file}.woff2`;
      cpSync(`fonts/ia-writer/${name}`, `media/fonts/${name}`);
      faces.push(`@font-face { font-family: '${f.family}'; font-style: ${style}; font-weight: ${weight}; font-display: swap; src: url(${name}) format('woff2'); }`);
    }
    cpSync('fonts/ia-writer/LICENSE.md', `media/fonts/licenses/${f.id}.md`);
  } else {
    const dir = `node_modules/${f.source.pkg}`;
    for (const css of f.source.css) {
      // Fontsource writes one commented block per subset: /* figtree-latin-wght-normal */
      for (const block of readFileSync(`${dir}/${css}`, 'utf8').split(/(?=\/\* )/)) {
        if (!/^\/\* [\w-]+?-latin(-ext)?-(wght|\d)/.test(block)) continue;
        const name = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
        cpSync(`${dir}/files/${name}`, `media/fonts/${name}`);
        faces.push(block.replace(/src:[^;]+;/, `src: url(${name}) format('woff2');`).trim());
      }
    }
    cpSync(`${dir}/LICENSE`, `media/fonts/licenses/${f.id}.txt`);
  }
  looks.push(
    `body[data-reading-font='${f.id}'] .mdr-layout { --doc-font: ${fontStack(f)}; --doc-leading: ${LEADING[f.group]};${f.size ? ` --doc-size: ${f.size};` : ''} }`,
    `.ff-${f.id} { font-family: ${fontStack(f)}; }`,
  );
}
writeFileSync('media/fonts/fonts.css', `/* Generated by esbuild.mjs from src/readingFonts.ts. Licenses: licenses/. */\n${faces.join('\n')}\n${looks.join('\n')}\n`);

// The Word export/import commands: a file of their own that the extension
// requires when one first runs, so start-up never reads it. The modules it
// shares with the extension (the renderer above all) come from the loaded
// extension bundle's `shared` export instead of a second copy.
const SHARED = ['render', 'commentStore', 'bibliography', 'localImage'];
const fromExtension = {
  name: 'from-extension',
  setup(b) {
    b.onResolve({ filter: new RegExp(`^\\./(${SHARED.join('|')})$`) }, (a) => ({ path: a.path.slice(2), namespace: 'extension' }));
    b.onLoad({ filter: /.*/, namespace: 'extension' }, (a) => ({ contents: `module.exports = require('./extension.js').shared.${a.path};`, loader: 'js' }));
  },
};

const builds = [
  // Extension host. Minified: less to read from disk (and scan, on Windows) at start-up.
  { entryPoints: ['src/extension.ts'], outfile: 'dist/extension.js', platform: 'node', format: 'cjs', external: ['vscode', './word.js'], minify: true, keepNames: true },
  { entryPoints: ['src/wordCommands.ts'], outfile: 'dist/word.js', platform: 'node', format: 'cjs', external: ['vscode', './extension.js'], plugins: [fromExtension], minify: true, keepNames: true },
  // Host core for tests / harness / CLI (no vscode dependency).
  { entryPoints: ['src/lib.ts'], outfile: 'dist/lib.cjs', platform: 'node', format: 'cjs' },
  // Webview.
  { entryPoints: ['webview/main.ts'], outfile: 'media/webview.js', platform: 'browser', format: 'iife', minify: true, keepNames: true },
];

for (const b of builds) {
  const opts = { bundle: true, target: 'es2022', sourcemap: false, logLevel: 'info', ...b };
  if (watch) await (await esbuild.context(opts)).watch();
  else await esbuild.build(opts);
}
